//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainService.MoneyRemoveService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MoneyRemoveService.IMoneyRemoveService")]
    public interface IMoneyRemoveService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneyRemoveService/RemoveMoneyFromAcc", ReplyAction="http://tempuri.org/IMoneyRemoveService/RemoveMoneyFromAccResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        bool RemoveMoneyFromAcc(string accountNumber, decimal moneyToRemove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneyRemoveService/RemoveMoneyFromAcc", ReplyAction="http://tempuri.org/IMoneyRemoveService/RemoveMoneyFromAccResponse")]
        System.Threading.Tasks.Task<bool> RemoveMoneyFromAccAsync(string accountNumber, decimal moneyToRemove);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMoneyRemoveServiceChannel : MoneyRemoveService.IMoneyRemoveService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MoneyRemoveServiceClient : System.ServiceModel.ClientBase<MoneyRemoveService.IMoneyRemoveService>, MoneyRemoveService.IMoneyRemoveService {
        
        public MoneyRemoveServiceClient() {
        }
        
        public MoneyRemoveServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MoneyRemoveServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoneyRemoveServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoneyRemoveServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RemoveMoneyFromAcc(string accountNumber, decimal moneyToRemove) {
            return base.Channel.RemoveMoneyFromAcc(accountNumber, moneyToRemove);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveMoneyFromAccAsync(string accountNumber, decimal moneyToRemove) {
            return base.Channel.RemoveMoneyFromAccAsync(accountNumber, moneyToRemove);
        }
    }
}
